workflows:
  default-workflow:
    name: Rally FE workflow
    instance_type: linux
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
        - firebase_credentials
        - azure_credentials
        - other
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master"
          include: true
          source: true
      cancel_previous_builds: false
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Installing Dependencies
        script: |
          set -e
          sudo apt-get update && sudo apt-get install -y curl jq
          echo "Installing dependencies..."
          flutter clean
          flutter pub get

      - name: Create .env file
        script: |
          set -e
          echo "Creating .env file..."
          echo "API_BACKEND_URL=$API_BACKEND_URL" > .env
          echo ".env file created with API_BACKEND_URL"

      - name: Generate l10n files
        script: |
          set -e
          echo "Generating localization files..."
          flutter gen-l10n

      - name: Setup Firebase
        script: |
          set -e
          echo "Installing Firebase CLI..."
          curl -sL https://firebase.tools | bash
          
          echo "Activating FlutterFire CLI..."
          dart pub global activate flutterfire_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          
          echo "Configuring Firebase..."
          flutterfire configure \
            --project=$FIREBASE_PROJECT_ID \
            --platforms=android \
            --android-package-name=$ANDROID_PACKAGE_NAME \
            --yes

      - name: Build Android
        script: |
          set -e
          echo "Building Android APK and AppBundle..."
          flutter build apk --release
          flutter build appbundle --release

      - name: Verify APK Signature
        script: |
          set -e
          echo "Verifying APK signature..."
          jarsigner -verify -verbose -certs build/app/outputs/flutter-apk/app-release.apk
          echo "✅ APK signature verified successfully!"

      - name: Get OAuth2 token
        script: |
          set -e
          echo "Fetching Microsoft Graph OAuth2 token..."
          TOKEN=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=$CLIENT_ID&scope=https://graph.microsoft.com/.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
            "https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token" | jq -r .access_token)

          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to obtain access token."
            exit 1
          fi

          echo "Token acquired."
          echo "TOKEN=$TOKEN" >> $CM_ENV

      - name: Upload Android build to SharePoint
        script: |
          set -e
          BASE_FOLDER="Frontend/Builds"

          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | tr -d '\r')
          VERSION_BUILD="${VERSION}+${BUILD_NUMBER}"
          PLATFORM_FOLDER="Android"
          BUILD_FOLDER="$BASE_FOLDER/$VERSION_BUILD/$PLATFORM_FOLDER"

          echo "Preparing Android upload → $BUILD_FOLDER"

          for FOLDER in "$BASE_FOLDER" "$BASE_FOLDER/$VERSION_BUILD" "$BUILD_FOLDER"; do
              echo "Ensuring folder exists: $FOLDER"
              EXISTS=$(curl -s -H "Authorization: Bearer $TOKEN" \
              "https://graph.microsoft.com/v1.0/sites/${SITE_ID}/drives/${DRIVE_ID}/root:/$FOLDER" | jq -r '.id // empty')
              echo "  Found $FOLDER"
              if [ -z "$EXISTS" ]; then
              # Create folder if not exist
              echo "  Creating $FOLDER..."
              FOLDER_RESPONSE=$(curl -s -X PUT \
                  -H "Authorization: Bearer $TOKEN" \
                  -H "Content-Type: application/json" \
                  -d '{"folder": {}, "@microsoft.graph.conflictBehavior": "fail"}' \
                  "https://graph.microsoft.com/v1.0/sites/${SITE_ID}/drives/${DRIVE_ID}/root:/$FOLDER")
              fi
          done

          upload_file() {
            local FILE_PATH="$1"
            local MIME_TYPE="$2"
            local FILE_NAME=$(basename "$FILE_PATH")

            if [ ! -f "$FILE_PATH" ]; then
              echo "File not found: $FILE_PATH — skipping"
              return
            fi

            echo "⬆ Uploading $FILE_NAME..."
            START_TIME=$(date +%s)

            RESPONSE=$(curl -s -w "%{http_code}" -o upload_result.json \
              -X PUT \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type: $MIME_TYPE" \
              --data-binary @"$FILE_PATH" \
              "https://graph.microsoft.com/v1.0/sites/${SITE_ID}/drives/${DRIVE_ID}/root:/$BUILD_FOLDER/$FILE_NAME:/content")

            END_TIME=$(date +%s)
            DURATION=$((END_TIME - START_TIME))

            if [ "$RESPONSE" != "201" ] && [ "$RESPONSE" != "200" ]; then
              echo "Upload failed for $FILE_NAME (HTTP $RESPONSE)"
              cat upload_result.json
              return
            fi

            FILE_WEBURL=$(jq -r '.webUrl' upload_result.json)
            echo "✅ Uploaded: $FILE_WEBURL"
            echo "⏱ Duration: ${DURATION}s"
          }

          upload_file "build/app/outputs/bundle/release/app-release.aab" "application/octet-stream"
          upload_file "build/app/outputs/flutter-apk/app-release.apk" "application/vnd.android.package-archive"

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - khang.nguyen@rally-go.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Send Teams Workflow Notification
          script: |
            #!/bin/bash
            source $CM_ENV
            
            # This script MUST run even if previous steps failed
            (
              VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | tr -d '\r' 2>/dev/null || echo "Unknown")
              VERSION_BUILD="${VERSION}+${BUILD_NUMBER}"

              if [ "$BUILD_SUCCESS" = "true" ]; then
                # SUCCESS payload for Teams Workflow
                PAYLOAD=$(cat <<EOF
            {
              "status": "success",
              "build_number": "${BUILD_NUMBER}",
              "version": "${VERSION_BUILD}",
              "branch": "${CM_BRANCH}",
              "commit": "${CM_COMMIT}",
              "url": "${CM_BUILD_URL}"
            }
            EOF
            )
              else
                # FAILURE payload for Teams Workflow
                PAYLOAD=$(cat <<EOF
            {
              "status": "failed",
              "build_number": "${BUILD_NUMBER}",
              "version": "${VERSION_BUILD}",
              "branch": "${CM_BRANCH}",
              "commit": "${CM_COMMIT}",
              "url": "${CM_BUILD_URL}"
            }
            EOF
            )
              fi

              # Send to Teams Workflow
              curl -X POST -H "Content-Type: application/json" \
                -d "$PAYLOAD" \
                "$TEAMS_WORKFLOW_URL"

              echo "Teams workflow notification sent"
            ) || echo "Warning: Teams notification failed but continuing..."