// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyzFT3u4XUcmRFDcOviAqdYZW1--pOFg',
    appId: '1:371906055890:web:fd99a57d7beb8e27a3e70b',
    messagingSenderId: '371906055890',
    projectId: 'rally-go-6',
    authDomain: 'rally-go-6.firebaseapp.com',
    storageBucket: 'rally-go-6.firebasestorage.app',
    measurementId: 'G-33GHYGR891',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbCDXsSAPGz4l1pLEPtH0I-Vgaj3-iD1Y',
    appId: '1:371906055890:android:6c9724bf6b2848a3a3e70b',
    messagingSenderId: '371906055890',
    projectId: 'rally-go-6',
    storageBucket: 'rally-go-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfQuSsuNMn40j8rQJYpJGgfQhPDH_uE0',
    appId: '1:371906055890:ios:27212ae44667bbc4a3e70b',
    messagingSenderId: '371906055890',
    projectId: 'rally-go-6',
    storageBucket: 'rally-go-6.firebasestorage.app',
    iosClientId: '371906055890-kvp9vg8hse7ja7sodkgqgl2qiq2u7eru.apps.googleusercontent.com',
    iosBundleId: 'com.example.rally',
  );
}
